# Generated by Django 5.2.1 on 2025-05-31 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Чоловіча'), ('F', 'Жіноча')], max_length=1, verbose_name='Стать')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зріст (см)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вага (кг)')),
                ('fitness_goal', models.CharField(blank=True, choices=[('lose_weight', 'Схуднення'), ('gain_muscle', "Набір м'язової маси"), ('fitness', 'Підтримка форми'), ('strength', 'Збільшення сили'), ('endurance', 'Витривалість'), ('rehabilitation', 'Реабілітація')], max_length=20, verbose_name='Фітнес ціль')),
                ('experience_level', models.CharField(choices=[('beginner', 'Початківець'), ('intermediate', 'Середній'), ('advanced', 'Просунутий')], default='beginner', max_length=20, verbose_name='Рівень підготовки')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Медичні обмеження')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name="Контакт для екстреного зв'язку")),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон екстреного контакту')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='Підписка на новини')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Detail',
                'verbose_name_plural': 'Clients Details',
            },
        ),
    ]
